#!/bin/sh -e

cd `dirname $0`

# Symbolically link configuration files
for f in `ls -a home | grep -v '\.$'`; do
	ln -sf `pwd`/home/$f ~/$f
done

# Symbolically link scripts
if [ ! -d ~/bin ]; then
	mkdir ~/bin
fi
for f in `ls bin`; do
	ln -sf `pwd`/bin/$f ~/bin/$f
done

# MacOS specific settings.
if [ `uname` = Darwin ]; then
	# Set faster key repeat.
	defaults write -g InitialKeyRepeat -int 14    # normal minimum is 15 (225 ms)
	defaults write -g KeyRepeat -int 1            # normal minimum is 2 (30 ms)

	# no more .DS_Store (maybe)
	defaults write com.apple.desktopservices DSDontWriteNetworkStores true

	# Dont steal focus on preview update.
	defaults write TeXShop BringPdfFrontOnAutomaticUpdate NO
fi
