#!/bin/sh -e
cd `dirname $0`

# Symbolically link configuration files
for f in `ls -a home | grep -v '\.$'`; do
	ln -sf `pwd`/home/$f ~/$f
done

# MacOS specific settings.
if [ `uname` = Darwin ]; then
	defaults write -g InitialKeyRepeat -int 14    # default is 15 (225ms)
	defaults write -g KeyRepeat -int 1            # default is 2 (30ms)
fi
